# Generated by Django 3.2.8 on 2022-05-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayhistorydiet',
            name='food_one_meal_g',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
