# Generated by Django 3.2.8 on 2022-03-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userworkoutinfo_last_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoutroutine',
            name='last_routine0_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userworkoutroutine',
            name='last_routine1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userworkoutroutine',
            name='last_routine2_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
