# Generated by Django 3.2.8 on 2022-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220313_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='target_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
