# Generated by Django 3.2.8 on 2022-03-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220318_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayhistoryuserinfo',
            name='target_kcal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
