# Generated by Django 3.2.8 on 2022-03-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workoutinfo_body_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayhistoryworkout',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayhistoryworkout',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
