# Generated by Django 3.2.8 on 2022-05-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20220322_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayhistoryworkout',
            old_name='end_Datetime',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='dayhistoryworkout',
            old_name='start_Datetime',
            new_name='start_datetime',
        ),
        migrations.AddField(
            model_name='dayhistoryworkout',
            name='kcal_consumption',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workoutinfo',
            name='workout_kcal',
            field=models.FloatField(),
        ),
    ]
