# Generated by Django 3.2.8 on 2022-05-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20220504_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dayhistoryworkout',
            old_name='kcal_consumption',
            new_name='workout_kcal_consumption',
        ),
    ]
