# Generated by Django 3.2.8 on 2022-03-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20220322_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayhistoryworkout',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='dayhistoryworkout',
            name='start_time',
        ),
        migrations.AddField(
            model_name='dayhistoryworkout',
            name='end_Datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dayhistoryworkout',
            name='start_Datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
