# Generated by Django 3.2.8 on 2022-05-16 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_auto_20220512_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayhistoryextraworkoutwrongposes',
            name='dayHistoryExtraWorkout_id',
        ),
        migrations.DeleteModel(
            name='DayHistoryExtraWorkout',
        ),
        migrations.DeleteModel(
            name='DayHistoryExtraWorkoutWrongPoses',
        ),
    ]
