# Generated by Django 3.2.8 on 2022-05-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_auto_20220516_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayhistoryworkout',
            name='is_extra_workout',
            field=models.BooleanField(default=False),
        ),
    ]
